// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WindowsFormsApp1.Data;

namespace WindowsFormsApp1.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240305140620_asdasd")]
    partial class asdasd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WindowsFormsApp1.Models.SinhVienModels", b =>
                {
                    b.Property<int>("MaSinhVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("HoVaTen")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Khoa")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Lop")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("SoDienThoai")
                        .HasColumnType("int");

                    b.HasKey("MaSinhVien");

                    b.ToTable("SinhVien");
                });
#pragma warning restore 612, 618
        }
    }
}
